### ISSUE TITLE
SQLite graph creation issue

### ISSUE THREAD

**Issue by maxg2k** [sualeh/SchemaCrawler-Docker#1]
Hi I'm getting the following error.  Any idea?

Feb 14, 2017 6:44:09 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.14.01
Feb 14, 2017 6:44:09 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line:
-server=sqlite
-user=
-password=*****
-database=/share/tasks.db
-tabletypes=TABLE
-infolevel=maximum
-routines=
-command=graph
-outputfile=/tmp/tasks_db.png
-loglevel=CONFIG
Feb 14, 2017 6:44:09 AM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Cannot perform operation: [SQLITE_ERROR] SQL error or missing database (near "graph": syntax error)
schemacrawler.schemacrawler.SchemaCrawlerException: Cannot perform operation: [SQLITE_ERROR] SQL error or missing database (near "graph": syntax error)
        at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:129)
        at schemacrawler.tools.executable.SchemaCrawlerExecutable.executeOn(SchemaCrawlerExecutable.java:120)
        at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:91)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:129)
        at schemacrawler.Main.main(Main.java:90)
**Caused by: java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "graph": syntax error)**
        at org.sqlite.DB.newSQLException(DB.java:888)
        at org.sqlite.DB.newSQLException(DB.java:899)
        at org.sqlite.DB.throwex(DB.java:866)
        at org.sqlite.NativeDB.prepare(Native Method)
        at org.sqlite.DB.prepare(DB.java:208)
        at org.sqlite.Stmt.execute(Stmt.java:144)
        at sf.util.DatabaseUtility.executeSql(DatabaseUtility.java:145)
        at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:118)
        ... 4 more

**Comment by sualeh** [comment]
This issue was moved to sualeh/SchemaCrawler#112
